amqp:
  host: amqp.partner.mcom.magento.com
  port: 22200
  user: luma
  password: luma
  vhost: luma

database:
  driver: pdo_sqlite
  user: auth
  password: auth
  path: database.sqlite
  memory: false
  doctrine_proxy_path: ./proxies