#!/usr/bin/php
<?php

require_once __DIR__.'/../vendor/autoload.php';

$app = new Silex\Application();

$app->register(new \Magento\Bootstrap\DependencyInjection\Provider\CommandProvider());
$app->register(new \Magento\Bootstrap\DependencyInjection\Provider\FixtureProvider());
$app->register(new \Magento\Bootstrap\DependencyInjection\Provider\ConfigurationProvider());
$app->register(new \Magento\Bootstrap\DependencyInjection\Provider\ApiProvider());
$app->register(new \Magento\Bootstrap\DependencyInjection\Provider\ServiceProvider());
$app->register(new \Magento\Bootstrap\DependencyInjection\Provider\DatabaseProvider());

$app['debug'] = true;

$app->boot();

$app['bootstrap.command.app']->run();